### Configuration File for FLARE Project

# If no value is entered for a key, the default value will be applied.

# General settings will be overwritten by container settings if different.

## General Settings
shared-directory          : /opt/flare
app-directory             : # /root/flare (default)
ssh-key:
  public                  :
  private                 :
git:
  remote:
    server                : # github.com (default)
    branch                : # master (default)
    user:
      name                :
      email               :
        
## flare-push-test Container Settings
flare-push-test:
  git:
    ssh-key:
      public              :
      private             :
    remote:
      server              : github.com
      repository          : vahid-dan/flare-push-test.git
      branch              : master
      user:
        name              :
        email             :
